title: Hello, world! I'm Kavya Murali Parthasarathy
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kavya Murali Parthasarathy # add your name
author-img: kavs_murali.JPG # add your photo
about-author: I am a neuroeconomist deeply fascinated by the interplay of quantum cognition and quantum mechanics.  
social-twitter: KavyaMuraliPar3 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Qetsiyeh # add your Github handle
social-linkedin: kavya-murali-parthasarathy-a76230b1 # add your Linkedin handle
social-email: kavyaparthasarathy92@gmail.com # add your Email address



# Disqus
discus-identifier: Kavs # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
